import {authenticate, AuthenticationBindings} from '@loopback/authentication';
import {inject} from '@loopback/core';
import {repository} from '@loopback/repository';
import {
  get,
  HttpErrors,
  post,
  requestBody,
  response,
  SchemaObject,
} from '@loopback/rest';
import {UserProfile} from '@loopback/security';
import {authorize} from '../authorization';
import {MerchantPayoutConfig, MerchantProfiles} from '../models';
import {MerchantProfilesRepository} from '../repositories';
import {
  MerchantPayoutConfigUpsertPayload,
  MerchantPayoutService,
} from '../services/merchant-payout.service';

type MerchantPayoutConfigView = Record<string, unknown> & {
  effectiveDailyCap: number;
  resolvedCommitmentEndAt?: Date;
  canStopAutoPayout: boolean;
  hasPrimaryBankAccount: boolean;
  canUpdateConfigToday: boolean;
  nextManualConfigChangeAllowedAt?: Date;
};

type MerchantPayoutConfigResponse = {
  success: boolean;
  message: string;
  merchantProfileId: string;
  config: MerchantPayoutConfigView | null;
};

const merchantPayoutConfigUpsertSchema: SchemaObject = {
  type: 'object',
  properties: {
    maxAllowedDailyCap: {
      type: 'number',
      description:
        'Maximum daily cap generated by the platform from the merchant statement.',
    },
    selectedDailyCap: {
      type: 'number',
      description:
        'Merchant-selected daily cap. If omitted or zero, the platform max cap is used.',
    },
    minimumPayoutAmount: {
      type: 'number',
      minimum: 0,
      description:
        'Minimum payout amount required before a batch is created. Use 0 to disable the minimum threshold.',
    },
    scheduleMode: {
      type: 'string',
      enum: ['eod', 'bucketed'],
      description:
        'Use eod for one payout at cutoff time or bucketed for recurring release windows.',
    },
    frequencyHours: {
      type: 'number',
      minimum: 0.01,
      maximum: 10,
      description:
        'Bucket size in hours. Fractional values are allowed for testing smaller intervals.',
    },
    startTime: {
      type: 'string',
      pattern: '^([01][0-9]|2[0-3]):[0-5][0-9]$',
      description:
        'Start time for payout scheduling in HH:mm format.',
    },
    cutoffTime: {
      type: 'string',
      pattern: '^([01][0-9]|2[0-3]):[0-5][0-9]$',
      description:
        'Cutoff time for payout scheduling in HH:mm format.',
    },
    timezone: {
      type: 'string',
      description:
        'Timezone used for payout scheduling. Currently Asia/Kolkata is supported.',
    },
    commitmentUnit: {
      type: 'string',
      enum: ['none', 'week', 'month'],
      description:
        'Commitment period unit for auto payout.',
    },
    commitmentValue: {
      type: 'number',
      minimum: 0,
      description:
        'Commitment period value. Required when commitmentUnit is week or month.',
    },
    commitmentStartAt: {
      type: 'string',
      format: 'date-time',
      description:
        'Commitment start datetime in ISO format.',
    },
  },
};

export class MerchantPayoutConfigController {
  constructor(
    @repository(MerchantProfilesRepository)
    public merchantProfilesRepository: MerchantProfilesRepository,
    @inject('service.merchantPayoutService.service')
    private merchantPayoutService: MerchantPayoutService,
  ) {}

  private async getCurrentMerchantProfile(currentUser: UserProfile) {
    const merchantProfile = await this.merchantProfilesRepository.findOne({
      where: {
        and: [{usersId: currentUser.id}, {isActive: true}, {isDeleted: false}],
      },
      order: ['createdAt DESC'],
    });

    if (!merchantProfile) {
      throw new HttpErrors.NotFound('Active merchant profile not found');
    }

    return merchantProfile;
  }

  private async getCurrentMerchantConfig(currentUser: UserProfile) {
    const merchantProfile = await this.getCurrentMerchantProfile(currentUser);
    const config = await this.merchantPayoutService.findConfigForMerchant(
      merchantProfile.id,
      currentUser.id,
    );

    return {
      merchantProfile,
      config,
    };
  }

  private async buildConfigView(
    config: MerchantPayoutConfig | null,
    usersId: string,
  ): Promise<MerchantPayoutConfigView | null> {
    if (!config) {
      return null;
    }

    const primaryBankAccount =
      await this.merchantPayoutService.getPrimaryMerchantBankAccount(usersId);

    return {
      ...config.toJSON(),
      effectiveDailyCap: this.merchantPayoutService.resolveEffectiveDailyCap(
        config,
      ),
      resolvedCommitmentEndAt:
        this.merchantPayoutService.resolveCommitmentEndAt(config),
      canStopAutoPayout:
        this.merchantPayoutService.canStopAutoPayout(config),
      hasPrimaryBankAccount: !!primaryBankAccount,
      canUpdateConfigToday:
        this.merchantPayoutService.canManuallyUpdateConfigToday(config),
      nextManualConfigChangeAllowedAt:
        this.merchantPayoutService.getNextManualConfigChangeAllowedAt(config),
    };
  }

  private async buildConfigResponse(
    merchantProfile: MerchantProfiles,
    config: MerchantPayoutConfig | null,
    message: string,
    usersId: string,
  ): Promise<MerchantPayoutConfigResponse> {
    return {
      success: true,
      message,
      merchantProfileId: merchantProfile.id,
      config: await this.buildConfigView(config, usersId),
    };
  }

  @authenticate('jwt')
  @authorize({roles: ['merchant']})
  @get('/merchant-payout-config/me')
  @response(200, {
    description: 'Fetch current merchant payout configuration',
  })
  async getMyConfig(
    @inject(AuthenticationBindings.CURRENT_USER) currentUser: UserProfile,
  ): Promise<MerchantPayoutConfigResponse> {
    const {merchantProfile, config} =
      await this.getCurrentMerchantConfig(currentUser);

    return this.buildConfigResponse(
      merchantProfile,
      config,
      config
        ? 'Merchant payout config fetched successfully'
        : 'Merchant payout config is not configured yet',
      currentUser.id,
    );
  }

  @authenticate('jwt')
  @authorize({roles: ['merchant']})
  @post('/merchant-payout-config/me')
  @response(200, {
    description: 'Create or update current merchant payout configuration',
  })
  async upsertMyConfig(
    @inject(AuthenticationBindings.CURRENT_USER) currentUser: UserProfile,
    @requestBody({
      required: true,
      content: {
        'application/json': {
          schema: merchantPayoutConfigUpsertSchema,
        },
      },
    })
    body: MerchantPayoutConfigUpsertPayload,
  ): Promise<MerchantPayoutConfigResponse> {
    const merchantProfile = await this.getCurrentMerchantProfile(currentUser);
    const existingConfig = await this.merchantPayoutService.findConfigForMerchant(
      merchantProfile.id,
      currentUser.id,
    );
    const config = await this.merchantPayoutService.upsertConfigForMerchant(
      merchantProfile.id,
      currentUser.id,
      body,
    );

    return this.buildConfigResponse(
      merchantProfile,
      config,
      existingConfig
        ? 'Merchant payout config updated successfully'
        : 'Merchant payout config created successfully',
      currentUser.id,
    );
  }

  @authenticate('jwt')
  @authorize({roles: ['merchant']})
  @post('/merchant-payout-config/me/stop')
  @response(200, {
    description: 'Request stop for automated merchant payouts',
  })
  async requestStop(
    @inject(AuthenticationBindings.CURRENT_USER) currentUser: UserProfile,
    @requestBody({
      required: false,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              stopReason: {
                type: 'string',
              },
            },
          },
        },
      },
    })
    body?: {stopReason?: string},
  ): Promise<MerchantPayoutConfigResponse> {
    const {merchantProfile, config} =
      await this.getCurrentMerchantConfig(currentUser);

    if (!config) {
      throw new HttpErrors.NotFound('Merchant payout config not found');
    }

    const result = await this.merchantPayoutService.requestAutoPayoutStop(
      config.id,
      body?.stopReason,
    );

    return this.buildConfigResponse(
      merchantProfile,
      result.config,
      result.message,
      currentUser.id,
    );
  }

  @authenticate('jwt')
  @authorize({roles: ['merchant']})
  @post('/merchant-payout-config/me/reactivate')
  @response(200, {
    description: 'Reactivate automated merchant payouts',
  })
  async reactivate(
    @inject(AuthenticationBindings.CURRENT_USER) currentUser: UserProfile,
  ): Promise<MerchantPayoutConfigResponse> {
    const {merchantProfile, config} =
      await this.getCurrentMerchantConfig(currentUser);

    if (!config) {
      throw new HttpErrors.NotFound('Merchant payout config not found');
    }

    const result = await this.merchantPayoutService.reactivateAutoPayout(
      config.id,
    );

    return this.buildConfigResponse(
      merchantProfile,
      result.config,
      result.message,
      currentUser.id,
    );
  }
}
